name: Build Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latex-talk.tex
      - uses: actions/upload-artifact@v2
        with:
          name: talk-slides
          path: latex-talk.pdf
